name: Build and Test Docker Image

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore test data
        run: cp data.json.orig data.json

      - name: Build Docker image
        run: docker build -t badmintonclub:latest .

      - name: Run Smoke Test and App Tests
        run: |
          docker run -d --name test-container badmintonclub:latest
          sleep 5
          docker logs test-container

      - name: Restore original test data
        run: docker exec test-container cp clubinfo.orig.json clubinfo.json

      - name: Run Playwright tests
        run: docker exec test-container npm test

      - name: Cleanup containers and images
        if: always()
        run: |
          docker stop test-container || true
          docker rm test-container || true
          docker rmi badmintonclub:latest || true
