name: Pull and Test Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  pull-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/badmintonclub:latest

      - name: Run container
        run: |
          docker run -d --name test-container -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/badmintonclub:latest
          sleep 5  # optional: wait for app to start
          docker logs test-container

      - name: Restore test data
        run: docker exec test-container cp data/clubinfo.orig.json data/clubinfo.json

      - name: Run Playwright tests
        run: docker exec test-container npm run test

      - name: Cleanup containers
        if: always()
        run: |
          docker stop test-container || true
          docker rm test-container || true
